### ISSUE TITLE
Linux workflow for save/load/show doesn't work

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/click4#7]
> 1. It seems it does not work when trying to load/save from the linux version. The app is not crashing but it's just doing nothing when pressing load or save. (I'm using the windows version that works well for now). Do you know if there is some more setup to do ?

**Comment by Darenn** [comment]
Here's the error code when clicking on "Show".

`** (process:37582): WARNING **: 13:25:09.907: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var
Traceback (most recent call last):
  File "/usr/bin/catfish", line 29, in <module>
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3.10/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3.10/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3.10/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
`

**Comment by josefnpat** [comment]
This thread suggests that it may be a bug in love: https://love2d.org/forums/viewtopic.php?t=80122

These docs suggest it should work: https://love2d.org/wiki/love.system.openURL

Will have to look into this more.

**Comment by josefnpat** [comment]
#12 may fix this
